MetaMask/auto-changelog

CHANGELOG.md, jest.config.js, package.json, src/changelog.js, src/changelog.test.js, src/cli.js, src/constants.js, src/index.js, src/index.test.js, src/parseChangelog.js, src/runCommand.js, src/updateChangelog.js, yarn.lock
This script has been migrated from the [`metamask-extension` repo](https://github.com/MetaMask/metamask-extension/blob/0dbd678f393ae141d207e35b0132e2ee8cb118e9/development/auto-changelog.js). Functionally it should behave almost identically. The differences are:
* It now gets the current version from [the `npm_package_version` environment variable](https://docs.npmjs.com/cli/v6/using-npm/scripts#packagejson-vars) instead of from the hard-coded path to the MetaMask extension manifest.
* The `CHANGELOG.md` file is now read from the current directory where the script is run, rather than from the hard-coded path to the `CHANGELOG.md` file in this repository.
* The repository URL is taken from the `npm_package_repository_url` environment variable instead of being hard-coded.
These changes can …
=> Migrate original `auto-changelog.js` script

README.md
Examples on how to use the CLI and the API have been added to the README. Reference documentation will be added in a later PR.
Relates to #17
=> Add usage docs to README

src/changelog.js, src/changelog.test.js, src/updateChangelog.js
The changelog can now be updated even when there are no tags. Previously it would break in `updateChangelog` when there was no most recent tag, and if you got past that it would put `vundefined` in the link definition for the "Unreleased" header. Now it is tolerant of there being no tags, and the repo URL is used for the link definition of the "Unreleased" header if there is no release to compare to.
Fixes #13
=> Allow updating changelog when there are no tags

package.json, src/cli.js, yarn.lock
`yargs` is now used for parsing CLI options and generating the `--help` text. This will make it easier to add new options.
=> Switch to `yargs`

src/cli.js
The description `test` was added for the `help` command when converting the CLI to use yargs. This description was accidentally left in and committed as part of #21.
=> Remove accidental test description for `help`

README.md, package.json, src/cli.js
The "update" action has been moved to a sub-command, in preparation for adding more commands in later PRs. Specifying a command has been made mandatory.
The `update-changelog` npm script has been renamed to `changelog`, to reflect that it will soon be used for more than just updates.
=> Move `update` to sub-command

src/changelog.js
The release header sorting was broken in two ways. First, the sort function was totally broken - it returned a boolean instead of the expected `-1` or `1`. Second, the release link generation would always consider the _numerical_ previous release to be the previous release for comparison purposes, even if it was released _after_.
The sorting function now correctly returns numbers, as `Array.prototype.sort` expects. The release link logic has been updated to ensure the "previous" release is both numerically and chronologically previous as well.
We don't yet validate that the releases are sorted chronologically, but that is the assumption for now. We can add validation using release dates at some point in the future.
=> Fix release header sorting

src/updateChangelog.js
The `updateChangelog` return value is now documented.
=> Add missing JSDoc `@return` description

src/cli.js, src/updateChangelog.js
Rather than always obtaining the 'currentVersion' of the project from an environment variable, it can now be passed in via a CLI flag instead.
Additionally, the validation for the version has been improved. It will now throw if the current version isn't a valid SemVer version, as our update logic depends upon it being valid. We also now ensure that the error message for a messing version is only printed when it was strictly required (it wasn't used for non-RC updates), and that the script terminates at that point.
Closes #10
=> Allow configuring 'currentVersion'

README.md, package.json, src/cli.js, src/generateDiff.js, src/generateDiff.test.js, src/index.js, src/validateChangelog.js, src/validateChangelog.test.js, yarn.lock
The validate command will validate the formatting of the changelog. If the `--rc` flag is used, it will also ensure that the current version is included as a release header, and that there are no unreleased changes.
The CLI command displays a rudimentary diff if formatting problems are detected. This can be improved later with colours, and with highlighting within each line to show what has changed. It also doesn't yet highlight whitespace changes.
The validation logic is also exposed via the API as a function called `validateChangelog`. It doesn't include the fancy diff output, but it does throw an error with all of the required information for someone to construct the same output.
Closes #11
=> Add `validate` command

src/cli.js, src/updateChangelog.js
The `root` parameter allows specifying the root project directory. This is used to resolve the changelog file path (unless an absolute path is specified), and it's used by the `update` command to ensure the search for changes since the last release only includes changes in the given root directory.
This new option is exposed via the API only on the `update` function, with the `rootProjectDirectory` option.
This was the last feature required for monorepo support.
Closes #34
=> Add `root` parameter

jest.config.js
We now collect coverage metrics for all files, rather than just those executed by tests.
=> Collect coverage metrics for all files

src/parseChangelog.js, src/parseChangelog.test.js
`parseChangelog.js` now has 100% test coverage. This includes two unit tests that demonstrate the undesired behaviour reported in #38.
These tests were added primarily to make it easier to fix #38 while ensuring the desired behaviour is preserved.
One branch was removed from `parseChangelog` because it was unreachable. Also a minor typo was fixed in a comment.
=> Add unit tests for `parseChangelog`

src/validateChangelog.js, src/validateChangelog.test.js
The command `auto-changelog validate --rc` would always fail claiming that there were Unreleased changes, even when there were none. This has been fixed, and a test has been added to capture this case.
=> Fix Unreleased changes detection

.github/dependabot.yml
This config only allows automatic updates for our packages.
=> Update to use standard Dependabot config

src/updateChangelog.js
We now throw an error if the current version already has a tag when updating the changelog. This helps protect users from accidentally updating the changelog before bumping the version.
Fixes #51
=> Throw error if current version tag exists when updating

src/parseChangelog.js, src/parseChangelog.test.js
Our `parseChangelog` function was mistakenly interpreting newlines between change categories as part of the change entry. Now it does not.
A new test has been added for this fix, along with a second one to verify that we're treating the newline between releases appropriately as well (this was working already but wasn't tested).
=> Fix mistaking newline between categories as part of change entry

src/updateChangelog.js
This PR fixes some faulty input validation in `updateChangelog`, which performed a strict equality check between a plain version string (e.g. `1.0.0`) and a version tag (e.g. `v1.0.0`), and would therefore always return `false`.
=> Fix tag and version equality check

src/parseChangelog.ts
The issue identified by this TODO comment did not exist after all. It has been replaced with a longer comment that explains why the following error is never encountered.
=> Replace TODO comment about missing test case

src/parseChangelog.test.ts, src/parseChangelog.ts, src/validateChangelog.test.ts
The change category is now validated as part of `parseChangelog`. Previously it was still being validated, but not until later on when the change categories were added to a `Changelog` instance. Validating it earlier in `parseChangelog` makes more sense now that we have types.
=> Validate change category during parsing

src/update-changelog.ts
The PR associated with a change has been moved to the end of the change entry, rather than being used as the prefix. This matches the "Keep A Changelog" style better, and generally makes the changelog easier to read. It also makes it easier to handle the case where one change was related to multiple PRs.
=> Move PR to end of change entry

src/update-changelog.ts
I accidentally introduced an error in #59, by failing to notice that some RegEx literals I moved around were not identical. Specifically, there was a capturing group around a `\d+` in one of the original literals but not the other. Compare these two lines: https://github.com/MetaMask/auto-changelog/blob/9c018fb8b98a40aaa0da1c08f4576b178d27c932/src/updateChangelog.js#L39-L40
This PR ensures that PR numbers are properly captured.
=> Fix updateChangelog PR number handling

package.json
Executing the CLI directly by invoking `./dist/cli.js` wasn't working because we never called `chmod +x` on it. This PR adds a call to `chmod` to the `build` package script.
In addition, it updates the package.json `bin` field to register two names for the application, `@metamask/auto-changelog` and `auto-changelog`. Previously, only the former (i.e. the name of the package) would be usable.
=> Update cli-related package.json scripts, fields

package.json
This will prevent us from publishing unused files. The is implemented per the module template. Uses `rimraf`.
=> Add build:clean script, use in prepublishOnly

src/changelog.ts, src/parse-changelog.test.ts
Adds two new methods `getRelease` and `getStringifiedRelease` to the `Changelog` class. This will allow us to retrieve changelog bodies to the bodies of release pull requests and/or GitHub releases in our GitHub Actions.
=> Add Changelog.getStringifiedRelease

package.json, src/cli.ts
If no `repo` parameter is supplied we get the GitHub repository URL from the environment variable `npm_package_repository_url`, which is set to the git repository URL if the `repository` field of `package.json` is set.
However, the git repository URL is not the same as the GitHub repository URL. The git repository URL ends with `.git`, but the GitHub repository URL does not. This discrepency wasn't noticed at first because the `repository` field in the `package.json` file for this project is malformed (the `.git` is missing).
The CLI has been updated to remove this extraneous `.git`, if it's present. So how the CLI will work whether the trailing `.git` is there or not. The `repository` entry for this project has been fixed as well.
=> Remove trailing '.git' from default repo URL

src/cli.ts, src/init.ts
This command generates an empty changelog. It doesn't list any changes or releases.
Closes #14
=> Add `init` command

src/changelog.ts, src/validate-changelog.test.ts
`auto-changelog` will now correctly update and validate changelogs where the first release chronologically is different than the first release numerically.
A test has been added to ensure such a changelog is now validated correctly. This test fails on `main`.
Fixes #57
=> Fix changelog where first release isn't first

.github/workflows/build-lint-test.yml, .yarnrc, README.md, package.json, yarn.lock
`@lavamoat/allow-scripts` is now used to selectively run post-install scripts. A `.yarnrc` file has been added to prevent scripts from running during the normal install command.
A "Contributing" section has been added to the README to explain how to install dependencies, along with other standard setup instructions.
=> Add `@lavamoat/allow-scripts` and `setup` command

.github/workflows/build-lint-test.yml
npm dependencies are now cached between CI runs. If a cache is found that used the same OS, Yarn version, and `yarn.lock` file, it is restored.
The `actions/cache@2` action (provided by GitHub) is used for caching. The way this action works is that it will restore the cache at the specified path if a matching cache is found. If no matching cache is found, it will run the job as normal and cache whatever it finds in that directory at the end of the job.
The Yarn cache directory is cached instead of `node_modules` because it contains the exact tarball that yarn downloaded from the registry, unaffected by post-install scripts. This is particularly important when using the `actions/cache@v2` action, because it can only create a cache at the end of a job. So we need to ensure the cached path …
=> Cache npm dependencies

.github/workflows/build-lint-test.yml
A "Validate changelog" step has been added to CI to validate the changelog on each PR. It will use the `--rc` flag as well when run on a release branch.
=> Validate changelog during CI

.github/workflows/build-lint-test.yml
The latest version of `actions/setup-node@v2` appears to act the same, except that it has better caching ([see here](https://github.com/actions/setup-node#v2)).
=> Use `actions/setup-node@v2` instead of `actions/setup-node@v1`

README.md
The README now includes the standard instructions about how to run the `lint` and `lint:fix` scripts.
=> Add instructions about the linter to the README

src/update-changelog.ts
The `update` command will filter out any commits that are the result of PRs that have been referenced already in the changelog.
Unfortunately this PR number detection only looked at the beginning of the entry. This was because prior to #66, that's where it would be by default (though this was always a poor decision, because it was always possible to update the change entry and reference the PR anywhere). This is especially broken since #66.
We now look for things that look like PR numbers anywhere in the change description.
=> Fix PR number detection in existing change entries

src/update-changelog.ts
We now detect all referenced PRs in each change description, rather than just the first. This is especially helpful when one change entry references many PRs (e.g. a set of related bug fixes).
Manual testing steps:
- Checkout this branch and run `yarn build`
- Run `yarn changelog update` a few times and observe how the duplicate detection works in the typical case where only one PR is referenced. After running this a few times the changelog should have one copy of each commit with a PR number, but multiple for the commit on this branch which has no number yet.
- Combine all unreleased change entries that include a PR number into a single change entry (e.g. indent them all once, that should do it).
- Run `yarn changelog update` again a few times and observe that the duplication detection …
=> Detect all PRs referenced in each change description

jest.config.js, src/index.ts, src/init.test.ts
I found myself in a position where I wanted to use `parseChangelog`. While we're here, we might as well export `createEmptyChangelog` and the `Changelog` class, as well. `import type { Changelog }` could be useful in TypeScript projects, for example.
=> Add more exports to index.ts

src/parse-changelog.test.ts, src/parse-changelog.ts
This enables the parsing of changelogs without a separating space in their `Unreleased` link reference definition. Changelog updating and validation remain unaffected by this change.
This package is very strict about formatting, however, we can afford to be somewhat lenient during parsing, and I think it's worthwhile to spare users from manually adding spaces to their link reference definitions.
=> Permit missing separating space in unreleased link reference definition

src/validate-changelog.test.ts, src/validate-changelog.ts
The validation command now ensures there are no uncategorized changes in RCs.
A few extra tests have been added to prevent coverage from dropping, due to how the code was reorganized.
=> Validate no uncategorized changes in RC

package.json, src/cli.ts, yarn.lock
The TypeScript update required adding an ESLint ignore comment for the URL import. A comment has been added explaining why we're doing that.
=> Update ESLint config for TypeScript and Jest to v7

src/validate-changelog.test.ts, src/validate-changelog.ts
Currently the `validate` command will ensure that no release has uncategorized changes when the `--rc` flag is present, but it doesn't care about uncategorized changes when the `--rc` flag isn't present.
This is against the spirit of the `--rc` flag. That flag should enable extra validation specific to the preparation of the current release. It shouldn't impose further burdens on maintainers that have nothing to do with the current release. This validation is also very inconvenient for some projects (e.g. `metamask-extension`), where the current maintainers may not have all of the context to make improvements to ancient changelog entries.
=> Skip validation of "Uncategorized" header for older releases

.github/workflows/build-lint-test.yml
When checking to see whether the current PR was for a release candidate or not, we were checking the wrong variable. `github.ref` contains the branch name if the action was triggered by a branch event, but in this case it's triggered by a `pull_request` event. For `pull_request` events, `github.ref` is set to `refs/pulls/[PR number]/merge`, so nothing was being recognized as a release candidate.
Instead it now checks `github.head_ref`, which is set to the branch name if it was triggered by `pull_request`. This workflow technically has two triggers: pushes to the `main` branch, and `pull_request`. But a push to the main branch is never a release candidate, so it's sufficient to just check `github.head_ref`.
Also the `yarn setup:postinstall` step was added, as it was missing from the …
=> Fix CI changelog validation step

src/cli.ts, src/repo.test.ts, src/repo.ts
In Yarn 3, `npm_package_repository_url` isn't set, and `auto-changelog` fails to parse the repository. In this PR I added a function which first looks at the `npm_package_repository_url`, and if that doesn't exist, looks at `PROJECT_CWD` instead. From there the `package.json` can be parsed in order to get the `repository` automatically.
For details on Yarn 3 environment variables, see [here](https://yarnpkg.com/advanced/lifecycle-scripts#environment-variables).
=> Read repository from package.json if `npm_package_repository_url` is not set

src/update-changelog.ts
When two tags are created in a repo that differ by mere milliseconds or
smaller, such as would happen in an automated high-level test of the
`create-release-pr` action, `git rev-list --tags` seems to get confused,
and so `getMostRecentTag` may not always return the latest tag. Adding
`--date-order` seems to fix this.
=> Account for tiny time differences between commits

.github/workflows/build-lint-test.yml, .github/workflows/create-release-pr.yml, .github/workflows/publish-release.yml
GitHub actions have been updated to resolve deprecation warnings.
For more details, see https://github.com/MetaMask/snaps-monorepo/pull/853
=> Update GitHub actions to resolve deprecation warnings

src/cli.ts
The CLI has been refactored to `return` on the same line an error is handled (by logging and setting the exit code). This is easier to read and less error prone (reduced risk of forgetting to `return`).
=> Refactor: `return` on same line as error

.github/workflows/build-lint-test.yml, .github/workflows/create-release-pr.yml, .github/workflows/publish-release.yml, package.json, scripts/prepack.sh
The GitHub actions have been updated to match the latest used in the module template, with some exceptions. The require-additional-reviewer action was omitted because it's broken for forks, and the documentation-related steps have been omitted because this repository does not yet have API documentation.
See: https://github.com/MetaMask/metamask-module-template/tree/a3b2e531a7961ccc32577ac3c49aa651a14623cd/.github/workflows
=> Update GitHub actions to match module template

package.json, src/cli.ts, tsconfig.build.json, tsconfig.json, yarn.lock
TypeScript has been updated to the latest stable version. Additionally, the version range has been updated to use `~` because TypeScript does not follow SemVer (they make breaking changes as minor updates).
The configuration has been updated to match the module template, except that two options (`exactOptionalPropertyTypes` and `noUncheckedIndexedAccess`) have been omitted temporarily to reduce the number of changes required for this update. They can be added in later PRs.
Just as in the module template, a separate `tsconfig` file has been created to distinguish build settings from settings used to compile unit tests.
The one configuration difference is the compilation target. The target is ES2019 here because this is a developer tool, so we don't need to stick to ES2017 for browser …
=> Update TypeScript to the latest stable version

src/parse-changelog.test.ts, src/parse-changelog.ts
Currently, this tool expects the version in a release header to be a version that looks like `<major>.<minor>.<patch>` and rejects other formats. However, it may be useful to publish a prerelease version of a package so that integration with other products/services can be tested in a more "live" manner, particularly if that package is a part of a monorepo. A prerelease version looks like
`<major>.<minor>.<patch>-<prerelease identifier>.<number>`, where `<prerelease identifier>` can be an arbitrary word like `alpha`, `beta`, or `rc`. This commit allows such versions.
=> Allow prerelease versions in release headers

package.json, src/changelog.ts, src/update-changelog.ts, yarn.lock
- [Replace `as T[]` assertions with `?? []`](https://github.com/MetaMask/auto-changelog/commit/53cf6735648f216ce3c8c5fe94f62cf078a63f2c) 
`as` assertions intended to exclude an empty/nullable type can be replaced by a nullish coalescing operator converting nullable values into an acceptable empty value that doesn't pollute the variable's type signature.
- [Replace `as` assertions with redundant type guards](https://github.com/MetaMask/auto-changelog/commit/f950f3e43d90403068c672eb00cbaa378bc77866) 
Sometimes TypeScript's type narrowing and inference doesn't fully work quite like it should. Even in these cases, using `as` assertions should be avoided.
It may seem like we know for certain what the type should be and there's no risk of it breaking, but there's always the possibility that …
=> Remove `as` assertions, or fix to mitigate the risk of silent failure

package.json, src/changelog.ts, yarn.lock
`@metamask/utils` has a development dependency on this package (since we need a way to validate its changelog). So, if this package depends on `@metamask/utils`, then that creates a circular dependency which could potentially cause issues. Since we only use one function from this package, we can just copy it.
---
See: https://github.com/MetaMask/utils/pull/153#issuecomment-1776854260
=> Avoid circular dependency on @metamask/utils

README.md
Update the CLI Usage section of the README to mention `--tag-prefix-before-package-name` and `--version-before-package-rename` so that they can be linked to.
=> Add usage for package rename options in README

src/cli.ts, src/update-changelog.ts
This pull request introduces enhancements that build upon previous modifications made in [PR #157](https://github.com/MetaMask/auto-changelog/pull/157), where we implemented tag history retention for renamed packages. However, those changes were initially applied only to the `changelog` `validate` `command`. With this current PR, we are extending the same functionality to the `changelog` `update` `command` as well.
* Fixes [#183] (https://github.com/MetaMask/auto-changelog/issues/183)
=> Extend tag history retention to changelog update command

README.md
Update the CLI Usage of `auto-changelog update` for renamed packages in the README to mention `--tag-prefix-before-package-name` and `--version-before-package-rename`.
=> Add changelog update usage for package rename options in README

src/update-changelog.ts
#158 incorrectly refactored the branches in updateChangelog, resulting in a state where new changelog entries weren't added to the return value if isReleaseCandidate is false.
- This error is fixed by moving the logic for retrieving new entries out of the if (isReleaseCandidate) block.
- The code for retrieving new entries is also extracted into its own method: getNewChangeEntries, abstracting away details that obscured the flow of the method's core logic.
- To verify that the buggy logic is correctly restored, it's necessary to compare the current state of updateChangelog to its state before the bug was introduced. For this, see: [diff link](https://github.com/MetaMask/auto-changelog/compare/e8df1ec717f534c8fe84c46ea86a847fa5a32973..da39a58a55571cf4e8a03e28096aa12c02c75f77#diff-4228e8302e …
=> Fix bug introduced to `updateChangelog` in #158

src/cli.ts
Since we're going to release some breaking changes, we may as well make Prettier the default.
It can be disabled by specifying `--no-prettier`.
=> BREAKING: Make Prettier the default option

README.md, src/changelog.test.ts, src/changelog.ts, src/cli.ts, src/parse-changelog.test.ts, src/parse-changelog.ts, src/update-changelog.ts, src/validate-changelog.test.ts, src/validate-changelog.ts
This commit adds a new option to the `validate` command, `--pr-links`, which will cause an error to be thrown if:
- a changelog entry does not have one or more links to pull requests after it
- a changelog entry does have PR links present, but they do not point to the project's repo
- a changelog entry does have PR links present, but they are not positioned at the very end of the line
The `ensureValidPrLinksPresent` option has also been added to `validateChangelog`.
If this option is provided, then `parseChangelog` is instructed to look for and extract pull request numbers from changelog entries. The list of numbers will then be checked for in the validation step. It is also used to reconstruct pull request links when the changelog is stringified.
Note that because this commit changes …
=> Add way to verify each change has associated PRs

.github/workflows/build-lint-test.yml, package.json
- Bump support for Node 18.x to at least 18.20
- Limit support for Node 20.x to at least 20.17
- Add support for Node 22 and higher
=> Sync supported Node versions w/ module template

.github/dependabot.yml, .github/pull_request_template.md, .github/workflows/build-lint-test.yml, .github/workflows/create-release-pr.yml, .github/workflows/main.yml, .github/workflows/publish-release.yml, scripts/get.sh
- Add pull request template
- Add compatibility test
- Use `action-checkout-and-setup` for checkout + setup Node tests
- Consolidate main workflows into `main.yml`
- Use artifacts for caching in release workflows
- Add Slack notification for releases
Note that this commit does not add docs publishing workflows or lint the changelog because `yarn build:docs` and `yarn lint:changelog` don't exist yet.
Closes #172.
Cross-check this PR with the `.github` directory in the module template: https://github.com/MetaMask/metamask-module-template/tree/main/.github
=> Sync GitHub workflows with module template

package.json, yarn.lock
- Use `ts-bridge` instead of `tsc` to generate a JavaScript build.
- This now produces two variants to cater to CommonJS-only and ESM-compatible bundlers.
- Define exports in `package.json`
- **BREAKING:** Custom, on-demand subpath imports are no longer supported.
- Run `yarn build` and inspect `dist`. You should see `.cjs`, `.mjs`, `.d.cts`, and `.d.mts` files for each TypeScript file in `src/`.
- Run `yarn test`. This now runs a second command, `attw --pack`, which verifies that the built files are correct. This should pass.
=> Use ts-bridge instead of tsc; restrict imports

CHANGELOG.md
Formatting changelog MD according to Release RP action generated code to prevent next release PR to include formatting changes.
See https://github.com/MetaMask/auto-changelog/pull/241#discussion_r2066955387
=> chore: formatting changelog

CHANGELOG.md, package.json, src/changelog.ts, src/cli.ts, src/constants.ts, src/get-new-changes.ts, src/parse-changelog.test.ts, src/parse-changelog.ts, src/repo.ts, src/run-command.ts, src/update-changelog.test.ts, src/update-changelog.ts, src/validate-changelog.test.ts, yarn.lock
Progresses: MetaMask/MetaMask-planning#5686
- Looks for `CHANGELOG entry:` in the PR description, and looks for `no-changelog` label, then applies this to the generated CHANGELOG
- Properly categorizes by Conventional Commit type, including our custom `ConventionalCommitType.RELEASE`
New parameters added:
- useChangelogEntry: boolean;
- useShortPrLink: boolean;
=> feat: parse `CHANGELOG entry:` and `no-changelog`
